### ISSUE TITLE
Railsbridge in Detroit, MI: Need assistance getting started.

### ISSUE THREAD

**Issue by lashawnd4u** [railsbridge/railsbridge_dot_org#100]
Good Day! I would like to have a Railsbridge workshop in Detroit.  I have been dipping in and out of coding for some years now. I have finally made a decision to embrace it fully, as well as other technologies. How can I get started in Detroit? I would love to have an introduction workshop before the end of May 2015.  I am super excited!

I look forward to a response.

**Comment by lilliealbert** [comment]
Awesome!!! 

To get started, you should open an issue on the Organizing repo: https://github.com/railsbridge/organizing/issues and we can help you get started.

We also have a very detailed cookbook with lots of documentation of how to run a workshop: https://github.com/railsbridge/docs/wiki/Cookbook

:tada: :tada: :tada:

**Comment by lashawnd4u** [comment]
Thanks so much. I am a bit confused with "open an issue". I thought that was this.  Oh boy don't I have a lot to learn? :-)  Can you provide me information on how to do that?  Thanks.

**Comment by lilliealbert** [comment]
No sweat — this is the repo for the RailsBridge website, and we use a different repo (https://github.com/railsbridge/organizing/issues) to deal with organizing things. This would be the right place to open an issue if you found a typo at railsbridge.org. :smile: 

So, do the same thing you did here, just in the other place.

Let me know if that makes more sense, or if that's just more confusing!

**Comment by lilliealbert** [comment]
Closing this issue — from the Eventbrite page, it looks like the Detroit RailsBridge was a sell-out success! :tada:
