### ISSUE TITLE
Video tutorials to accompany curriculums

### ISSUE THREAD

**Issue by dannyshafer** [railsbridge/railsbridge_dot_org#101]
Hi everyone! :) 

I've been volunteering at a couple RB events and it's come up in conversation that it might be nice to have video tutorials to accompany the curriculums so that people can follow along as they go (both in the workshops and if they're going through the curriculum on their own). I'd be happy to make them but just wanted to get a thumbs up from someone to confirm that it'd be a good addition to the site. I'm thinking one video for each of the three Rails tutorials since those are the ones I've done in workshops. Thoughts?

**Comment by ruchikakumar** [comment]
That sounds like a great idea! A huge undertaking no?

**Comment by lilliealbert** [comment]
I'd love to hear more about the specifics of the content you would be
producing. A lot of the value of RailsBridge workshops is the stuff you get
from the instructor, and I wouldn't want to turn a class of people talking
to each other into a room of people with headphones on.

Are you thinking a Railscasts-style walkthrough of the entire curriculum?

I do worry that this would make life more difficult for teachers, rather
than less.

On Tue, May 12, 2015 at 5:57 AM, ruchikakumar <notifications@github.com>
wrote:

> That sounds like a great idea! A huge undertaking no?
>
> On Mon, May 11, 2015 at 8:08 PM, Daniel Shafer <notifications@github.com>
> wrote:
>
>
> > Hi everyone! :)
> >
> > I've been volunteering at a couple RB events and it's come up in
> > conversation that it might be nice to have video tutorials to accompany
> the
> > curriculums so that people can follow along as they go (both in the
> > workshops and if they're going through the curriculum on their own). I'd
> be
> > happy to make them but just wanted to get a thumbs up from someone to
> > confirm that it'd be a good addition to the site. I'm thinking one video
> > for each of the three Rails tutorials since those are the ones I've done
> in
> > workshops. Thoughts?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> http://t.senalquatro.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1pty-nW3zbVmv41QW53F3J29CHy_XYf4f7xxW03?t=https%3A%2F%2Fgithub.com%2Frailsbridge%2Frailsbridge_dot_org%2Fissues%2F101&si=6444418971729920&pi=98d4c535-1a22-455a-a0c1-5176430a950f
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/railsbridge_dot_org/issues/101#issuecomment-101266451>
> .
>



-- 
Lillie Chilen
@lilliealbert
('li-lee shuh-'leen)

**Comment by dannyshafer** [comment]
@ruchikakumar Well yes, but it'd be fun and worth it. :)

@lilliealbert I don't think it would turn into that. From my experience, there's only been one time that the whole class went through the curriculum together. The other times it's been everyone fending for themselves (with a nearby TA like me to help). My videos wouldn't be intrusive at all, just linked at the beginning of each curriculum to basically say "if you want to see a walkthrough of this tutorial, it's here for you". As it is now, I typically go through the tutorial each workshop with the student sitting next to me and we talk through each part. With a video, they could refer back and so on. For people who don't have the luxury of learning in person, this will be invaluable. Video tutorials taught me a huge chunk of what I know because of people showing their knowledge online and I'd like to contribute for others.

**Comment by lilliealbert** [comment]
@dannyshafer If this is still something you're interested in pursuing, I'd suggest making a short demo video and making a PR with it — maybe the first few pages of the Suggestotron curriculum?

I'm still a bit dubious about adding videos, but if you made one and put it online, it could be valuable whether or not it became part of the official RailsBridge curriculum. 

(There are a lot of tutorials online that are focused on individual remote learners, so I'm not particularly interested in moving the RailsBridge curriculum in that direction.)
