### ISSUE TITLE
Check approval status for the event I created?

### ISSUE THREAD

**Issue by hanzbonanz** [railsbridge/railsbridge_dot_org#104]
Hi, 

I tried to add an event to RailsBridge 6 days ago but it has not been approved yet.  Is there a way I can check the status?  I'm just concerned that the event data did not get saved to the database since I did not receive a confirmation e-mail, just a confirmation page that the event had been created.

Thanks!
Hanna

**Comment by hanzbananz** [comment]
problem solved, event is up.

**Comment by lilliealbert** [comment]
:+1:
