### ISSUE TITLE
Dead External URLs Throughout App

### ISSUE THREAD

**Issue by murjax** [railsbridge/railsbridge_dot_org#120]
I have detected that the following external links are dead. Most are 404s, with some 500s and 999s. 

1
destination: https://www.omniref.com/,
origin: http://railsbridge.org/learn/resources

2
destination: https://www.omniref.com/ruby/gems/activerecord,
origin: http://railsbridge.org/learn/resources

3
destination: https://www.omniref.com/ruby/gems/json,
origin: http://railsbridge.org/learn/resources

4
destination: https://www.omniref.com/ruby/gems/rake,
origin: http://railsbridge.org/learn/resources

5
destination: https://www.omniref.com/ruby/gems/activerecord/4.1.1/symbols/ActiveRecord::Scoping::Named#annotation=28,
origin: http://railsbridge.org/learn/resources

6
destination: http://www.sfruby.info/,
origin: http://railsbridge.org/about

7
destination: http://www.linkedin.com/pub/isa-herico/4a/9/298,
origin: http://railsbridge.org/about/team

8
destination: http://onales.com/,
origin: http://railsbridge.org/about/sponsors

9
destination: http://rubyfuza.org/,
origin: http://railsbridge.org/about/sponsors

10
destination: http://mkf.org/,
origin: http://railsbridge.org/about/sponsors

11
destination: http://www.neo.com/,
origin: http://railsbridge.org/about/sponsors

12
destination: http://weworkhappy.com/,
origin: http://railsbridge.org/about/sponsors

13
destination: http://www.meetup.com/Portland-RailsBridge/,
origin: http://railsbridge.org/about/chapters

14
destination: http://www.railsbridgeindy.org/,
origin: http://railsbridge.org/about/chapters

15
destination: http://railsbridgedc.com/,
origin: http://railsbridge.org/about/chapters

16
destination: http://www.meetup.com/RailsBridgeMx/,
origin: http://railsbridge.org/about/chapters

17
destination: http://rubysavannah.com/events/1,
origin: http://railsbridge.org/about/past-events

18
destination: http://www.railsbridgeboston.org/blog/2013_mar_recap,
origin: http://railsbridge.org/about/past-events

19
destination: http://www.railsbridgeboston.org/blog/2013_jan_recap,
origin: http://railsbridge.org/about/past-events

20
destination: http://www.railsbridgeboston.org/blog/2012_nov_recap,
origin: http://railsbridge.org/about/past-events

21
destination: http://www.railsbridgeboston.org/blog/2012_aug_recap,
origin: http://railsbridge.org/about/past-events

22
destination: http://www.sfruby.info/events/52502132/,
origin: http://railsbridge.org/about/past-events

23
destination: http://www.sfruby.info/events/14836042/,
origin: http://railsbridge.org/about/past-events

**Comment by tjgrathwell** [comment]
Thanks a ton, all the problem links should be fixed or removed now.

A couple of them did seem to work after all, like the linkedin link and the rubyfuza link. Though the rubyfuza site didn't work initially, it's probably on a free Heroku app and takes time to spin up.
