### ISSUE TITLE
Application Error on homepage

### ISSUE THREAD

**Issue by wassimk** [railsbridge/railsbridge_dot_org#124]
On the main website I'm getting a generic Heroku application error page:

![2017-12-18_20-18-55](https://user-images.githubusercontent.com/2261839/34137450-b082ecf0-e430-11e7-8020-91560b645091.png)

**Comment by tjgrathwell** [comment]
It's back up now, seems like Heroku started more aggressively enforcing uptime limits for free apps. I've bumped https://railsbridge.org https://docs.railsbridge.org to Hobby level.
