### ISSUE TITLE
docs ask to use ruby version 2.3 but this is not supported by Heroku

### ISSUE THREAD

**Issue by lzhengem** [railsbridge/railsbridge_dot_org#132]
The docs from http://docs.railsbridge.org/installfest/osx_rvm is instructing students to install ruby version 2.3, and then later asks them to deploy to Heroku. Version 2.3 is not supported by Heroku-18, so it generates this following error:

        This version of Ruby is not available on Heroku-18. The minimum supported version
        remote:  !     of Ruby on the Heroku-18 stack can found at:
        remote:  !     
        remote:  !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes    

Perhaps a compatible version should be used instead for download.

**Comment by ultrasaurus** [comment]
updated to ruby-2.5.6
