### ISSUE TITLE
Would like Rails Bridge to Come to Korea

### ISSUE THREAD

**Issue by Toddsqui** [railsbridge/railsbridge_dot_org#95]
As I write this, I am part of a group in Busan, South Korea called "Busan Coders," (http://busancoders.com/). There are about seven of us in a group and we all come from varied backgrounds and experiences and work history; but more importantly, we are all part of this group because we have an interest in learning to code! We are all basically novices when it comes to learning Ruby (and Rails). Right now, the three of us in the group are trying to learn Ruby through the Hartl tutorials and various other means, but it is still very difficult without the careful eye of a mentor or instructor who has trudged the same path, so to speak. For the moment, we are handling ourselves pretty given the limited experiences we have, but we would love it if someone could bring Ruby Bridges to our group in Busan, South Korea! Ruby is starting to gain some traction and popularity here, and it would be wonderful if you could help us speed up that popularity by running your conference for our group here in Busan (or possibly Seoul, as we have some connections to other aspiring programmers in that city).

Please let me know if there is anyone I can speak to about making this happen, or if there is any way I can open up a dialogue about bringing Rails Bridge to Korea!

I would like to thank you in advance for taking the time consider this post.

Sincerely,

Todd Squitieri

**Comment by lilliealbert** [comment]
Closing this issue since it's been a while! @Toddsqui, if you have other workshop ideas, feel free to open another issue in the Organizing repo: https://github.com/railsbridge/organizing/issues.

:grinning:
